# CMEE 2019 HPC excercises R code HPC run code proforma

rm(list=ls()) # good practice 
try(dev.off(), silent = T) # try to close any active devices, if there are no devices active ingore the error produced.

source("db319_HPC_2019_main.R") # laod functions

#### Q18 #####

as.numeric(Sys.getenv("PBS_ARRAY_INDEX")) # uncomment when running on the cluster

# iter <- 3 ##for local testing only, comment out when on cluster

speciation_rate <- 0.005502 # speciation rate generated by `get_my_speciation_rate.R`


set.seed(iter) # set the seed for the run
iter_range <- 100 # number of iterations for defining how many runs of each community size to use below, should be devisible by 4

# rotate through different community sizes
if(1 <= iter & iter <= iter_range*0.25) size = 500 # if the first 25% of iterations size = 500 and so on 

if(iter_range*0.25 < iter & iter <= iter_range*0.5) size = 1000

if(iter_range*0.5 < iter & iter <= iter_range*0.75) size = 2500

if(iter_range*0.75 < iter & iter <= iter_range) size = 5000

FileName = paste("Cluster_Run_output", iter, ".rda", sep = '') #create file name for this iteration

cluster_run(speciation_rate = speciation_rate, size = size, wall_time = 1, interval_rich = 1, interval_oct = floor(size/10), burn_in_generations = 8*size, output_file_name = FileName)








